### ISSUE TITLE
Change names

### ISSUE THREAD

**Issue by talgalili** [dirmeier/datastructures#11]
When loading the package I get:

```
The following objects are masked from ‘package:utils’:

    head, stack

The following objects are masked from ‘package:base’:

    get, remove
```

The functions head and get are very basic (also stack and remove), to override them in the working environment is likely to break things for people. It is probably better to either make these functions generic or to change their names.

**Comment by dirmeier** [comment]
Hey, the function names have been changed with version `v0.2.8` for the JOSS review. I only havent submitted it to CRAN yet, because I wanted to add suffix trees/arrays....

I really appreciate the time you put into pointing all these things out and that you use the package. I recently haven't found much time to update the package..

**Comment by talgalili** [comment]
No worries, and thanks for developing the package.
I'm teaching an intro to CS with R, and was hoping to find a package to demonstrate how stacks have an O(1) insertion that is practically faster than the option with array copying done in R.
So far, the benchmark doesn't prove this point. If you can figure this out, it would be cool. (if not, no worries, it's just bring the question if it would have been faster to just implement stack in R, even though the data structure is not really a linked list, and that would still work faster...)

**Comment by dirmeier** [comment]
Cool, I will try to hurry this up. Nice to see that it has some use...
